name: Test Linux

on:
  pull_request:
    paths-ignore:
      - README.md
      - .github/**
      - '!.github/workflows/test-linux.yml'
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
      - canary
      - v[0-9]+.x-staging
      - v[0-9]+.x
    paths-ignore:
      - README.md
      - .github/**
      - '!.github/workflows/test-linux.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.11'
  FLAKY_TESTS: keep_retrying

permissions:
  contents: read

jobs:
  test-linux:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9  # v3.5.3
        with:
          persist-credentials: false
          path: node
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1  # v4.7.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: make -C node build-ci -j2 V=1 CONFIG_FLAGS="--error-on-warn"
      - name: Test
        run: make -C node run-ci -j2 V=1 TEST_CI_ARGS="-p actions --measure-flakiness 9"
      - name: Re-run test in a folder whose name contains unusual chars
        run: |
          mv node 'dir%20with unusual"chars '"'"'åß∂ƒ©∆¬…`'
          cd 'dir%20with unusual"chars '"'"'åß∂ƒ©∆¬…`'
          ./tools/test.py --flaky-tests keep_retrying -p actions -j 2
